# Generated by Django 3.0.7 on 2020-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('latin_name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('discovered', models.CharField(max_length=100)),
                ('electron_shell', models.CharField(max_length=20)),
                ('electrons', models.CharField(max_length=100)),
                ('protons', models.CharField(max_length=100)),
                ('neutrons', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('atomic_number', models.CharField(max_length=100)),
                ('atomic_weight', models.CharField(max_length=100)),
                ('density', models.CharField(max_length=100)),
                ('melting', models.CharField(max_length=100)),
                ('boiling', models.CharField(max_length=100)),
                ('phase', models.CharField(max_length=100)),
                ('valence_electron', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('electronic_config', models.CharField(max_length=100)),
                ('oxidation_state', models.CharField(max_length=100)),
                ('atomic_radius', models.CharField(max_length=100)),
                ('covalent_radius', models.CharField(max_length=100)),
                ('vander_radius', models.CharField(max_length=100)),
                ('electronegativity', models.CharField(max_length=100)),
                ('electronaffinity', models.CharField(max_length=100)),
                ('magnetic_type', models.CharField(max_length=100)),
                ('crystal_str', models.CharField(max_length=100)),
                ('resistivity', models.CharField(max_length=100)),
                ('superconducting_point', models.CharField(max_length=100)),
            ],
        ),
    ]
