# Generated by Django 3.0.7 on 2020-07-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='electron_shell',
            field=models.CharField(max_length=50),
        ),
    ]
