# Generated by Django 3.0.7 on 2020-07-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20200701_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='elements',
            new_name='Post',
        ),
    ]
